stages:
- stage: deploy
  jobs:
  - deployment: DeployWeb
    displayName: deploy Web App
    pool: DemoPool
    # creates an environment if it doesn't exist
    environment: 
      name: 'DemoEnv'
      resourceName: allien
      resourceType: virtualMachine
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo Hello world
          - script: echo '$(Pipeline.Workspace)'
        #workspace:
#clean: all
